version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:32767
functions:
  email:
    lang: python3-http
    handler: ./email
    image: quay.io/harikube/example-webshop-service-email:latest
    secrets:
      - example-webshop-service-smtp-details
