# This rule is not used by the project example-webshop-service itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to product.webshop.harikube.info resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: example-webshop-service
    app.kubernetes.io/managed-by: kustomize
  name: order-viewer-role
rules:
- apiGroups:
  - product.webshop.harikube.info
  resources:
  - orders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - product.webshop.harikube.info
  resources:
  - orders/status
  verbs:
  - get
