# This rule is not used by the project example-webshop-service itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over product.webshop.harikube.info.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: example-webshop-service
    app.kubernetes.io/managed-by: kustomize
  name: product-admin-role
rules:
- apiGroups:
  - product.webshop.harikube.info
  resources:
  - products
  verbs:
  - '*'
- apiGroups:
  - product.webshop.harikube.info
  resources:
  - products/status
  verbs:
  - get
